/**
 * 报表功能注册表（唯一配置入口）。
 * - menu: false → 侧栏隐藏（删菜单只改这里，勿删 api/视图文件）
 * - hub: false → 报表中心首页不展示入口
 * - enabled: false → 强制下线（即使文件还在）
 * 路由/菜单仅注册「enabled + 视图文件存在 + api 文件存在（若声明）」的项，缺文件不会拖垮整站。
 */
export const REPORT_CATALOG = [
  {
    id: 'wip',
    routePath: 'wip',
    viewFile: 'WipReportView.vue',
    apiFile: 'wip.js',
    title: '在制品报表',
    description: '按工单查看工序与在制数量（wip 口径）',
    icon: 'Document',
    menu: true,
    hub: true,
    enabled: true,
  },
  {
    id: 'daily-output',
    routePath: 'daily-output',
    viewFile: 'DailyOutputReportView.vue',
    apiFile: 'dailyOutput.js',
    title: '日产报表',
    description: '按日 / 产线 / 产品查看计划与实际产量',
    icon: 'DataAnalysis',
    menu: true,
    hub: true,
    enabled: true,
  },
  {
    id: 'employee-work-hours',
    routePath: 'employee-work-hours',
    viewFile: 'EmployeeWorkHourReportView.vue',
    apiFile: 'employeeWorkHours.js',
    title: '员工工时报表',
    description: 'MES 报工记录按员工汇总工时，支持日期、部门、员工筛选与 Excel 导出',
    icon: 'Timer',
    menu: true,
    hub: true,
    enabled: true,
  },
  {
    id: 'equipment-oee',
    routePath: 'equipment-oee',
    viewFile: 'EquipmentOeeReportView.vue',
    apiFile: 'equipmentOee.js',
    title: 'OEE 设备报表',
    description: 'OEE、稼动率、开机率与停机时长分析，支持趋势图与 Excel 导出',
    icon: 'DataAnalysis',
    menuGroup: 'equipment',
    menu: true,
    hub: true,
    enabled: true,
  },
  {
    id: 'equipment',
    routePath: 'equipment',
    viewFile: 'EquipmentReportView.vue',
    apiFile: null,
    title: '设备台账',
    description: '设备档案台账查询，按编号/名称/部门/状态筛选',
    icon: 'Cpu',
    menuGroup: 'equipment',
    menu: true,
    hub: true,
    enabled: true,
  },
  {
    id: 'equipment-repairs',
    routePath: 'equipment-repairs',
    viewFile: 'EquipmentRepairReportView.vue',
    apiFile: 'equipmentRepair.js',
    title: '设备维修报表',
    description: '维修工单明细：设备、故障时间、故障现象、维修人、耗时与状态',
    icon: 'Tools',
    menu: false,
    hub: false,
    enabled: true,
  },
  {
    id: 'equipment-inspection',
    routePath: 'equipment-inspection',
    viewFile: 'EquipmentInspectionReportView.vue',
    apiFile: 'equipmentInspection.js',
    title: '设备点检报表',
    description: '按设备与时间查询点检明细，含点检项、结果、点检人与点检时间',
    icon: 'List',
    menu: false,
    hub: false,
    enabled: true,
  },
  {
    id: 'equipment-maintenance',
    routePath: 'equipment-maintenance',
    viewFile: 'EquipmentMaintenanceReportView.vue',
    apiFile: 'equipmentMaintenanceReport.js',
    title: '设备保养报表',
    description: '保养计划执行情况与保养记录明细，支持条件查询与 Excel 导出',
    icon: 'Calendar',
    menu: false,
    hub: false,
    enabled: true,
  },
]
